### ISSUE TITLE
Calling re-factoring

### ISSUE THREAD

**Issue by typfel** [wireapp/wire-ios-sync-engine#190]
## Problem
With the introduction of calling V3 we will have two code paths for calling and I don't want these two code paths to interfere with each other. Having the VoiceChannel in `data-model` together with the voice channel observers and conversation list makes this difficult.

Because:
- Most of the voice channel functionality is added via categories  in sync-engine so it can't be overridden.
- the current observers force me translate `V3` call state to `V2` and can fire when I don't want them to.
- voice channel observers & conversation list force me to include `avs` and `WireCallCenter` in the data model.

## Possible solution
- Move voice channel observers to sync-engine and have separator observers for `V2` and `V3`. They can then be hidden behind a wrapper observer.
- Voice channel conversation list can be removed since we don't have a fullscreen call UI now
- If the two above points have been done we can move all calling related classes into `sync-engine` and drop the `avs` dependency.

**Comment by daehn** [comment]
@typfel is this issue still valid?

**Comment by typfel** [comment]
No :)
