### ISSUE TITLE
UI API are called in background thread

### ISSUE THREAD

**Issue by crystalztl** [wireapp/wire-ios-sync-engine#771]
1.  LocalNotificationDispatcher.swift  line 84;
2. BackgroundAPNSConfirmationStatus.swift line:35;
3. ZMLocalNotificationSet.swift line: 107

**Comment by mikeger** [comment]
Hey @crystalztl ! Thanks for noticing the issue, we'll be looking into refactoring those parts of code in order to make them not to use from the background thread the Apple APIs, that are designed to be used only from the main thread.

**Comment by alexaubry** [comment]
This was fixed when dropping iOS 9 and adopting the new notification system.
