### ISSUE TITLE
Port to Swift 3 progress

### ISSUE THREAD

**Issue by daehn** [wireapp/wire-ios-sync-engine#78]
**This issue is here to track the progress of porting to Swift 3.0**

* Checking the automation has been done from `/Tests/Source/E22E/OtrBaseTests` until `/Tests/Source/Strategies/DeleteAccountRequestStrategyTests` in the tests

* All the files in the sources directory has been checked but the migrator missed many changes completely. I would suggest just trying to build and see which error appear.

**Comment by marcoconti83** [comment]
I'm resuming checking the test from `/Tests/Source/Strategies/DeleteAccountRequestStrategyTests`
