### ISSUE TITLE
Xcode 10 Migration

### ISSUE THREAD

**Issue by alexaubry** [wireapp/wire-ios-sync-engine#851]
We use this issue to track the progress of Xcode 10 migration for Sync Engine. For UI dependencies, see https://github.com/wireapp/wire-ios/issues/2657.

✅ = released
🔴 = failing tests
🔵 = pending release
➡️ = TBD

State | Dependency | Member | PR | Version
------|------------- | ------ | ------------- | ----------
✅ | [wire-ios-system](https://github.com/wireapp/wire-ios-system) | @alexaubry | https://github.com/wireapp/wire-ios-system/pull/32 | 24.0.0 |
✅  | [wire-ios-testing](https://github.com/wireapp/wire-ios-testing) | @alexaubry  | https://github.com/wireapp/wire-ios-testing/pull/22 | 17.0.0|
✅ | [wire-ios-utilities](https://github.com/wireapp/wire-ios-utilities) | @alexaubry | https://github.com/wireapp/wire-ios-utilities/pull/55 | 26.0.0 |
✅ | [wire-ios-cryptobox](https://github.com/wireapp/wire-ios-cryptobox) | @alexaubry | https://github.com/wireapp/wire-ios-cryptobox/pull/24 | 16.0.0 |
✅ | [wire-ios-images](https://github.com/wireapp/wire-ios-images) | @alexaubry | https://github.com/wireapp/wire-ios-images/pull/18 | 19.0.0 |
✅ | [wire-ios-transport](https://github.com/wireapp/wire-ios-transport) | @alexaubry | https://github.com/wireapp/wire-ios-transport/pull/103 | 42.0.0 |
✅ | [HTMLString](https://github.com/wireapp/HTMLString) | @alexaubry | [wireapp/HTMLString](https://github.com/wireapp/HTMLString/releases/tag/4.0.2-xcode_10) | 4.0.2-xcode_10 |
✅ | [wire-ios-link-preview](https://github.com/wireapp/wire-ios-link-preview) | @alexaubry | https://github.com/wireapp/wire-ios-link-preview/pull/34 | 13.0.0 |
✅ | [wire-ios-mocktransport](https://github.com/wireapp/wire-ios-mocktransport)  | @alexaubry  | https://github.com/wireapp/wire-ios-mocktransport/pull/92 | 82.0.0 |
✅ | [wire-ios-data-model](https://github.com/wireapp/wire-ios-data-model) | @alexaubry  |  https://github.com/wireapp/wire-ios-data-model/pull/554 | 121.0.0 |
✅ | [wire-ios-request-strategy](https://github.com/wireapp/wire-ios-request-strategy) | @alexaubry | https://github.com/wireapp/wire-ios-request-strategy/pull/77 | 101.0.0 |

**Comment by vytis** [comment]
@zenkins release major
